### ISSUE TITLE
Attributes junction tables should prohibit duplicate data via index

### ISSUE THREAD

**Issue by murwiz** [interchange/interchange6-schema#112]
Some of the various "*_attributes tables:

navigation_attributes
product_attributes
user_attributes

allow duplicate data (e.g., you can have a particular paring of sku and attributes ID in the product_attributes table more than once). This has no practical value and in fact complicates the use of the table in SQL queries. (I'm not quite sure what it does to DBIC; it may be harmless there.)

I advise that these tables include a UNIQUE declaration on the combination of the two FK values to prevent this.

**Comment by SysPete** [comment]
I agree with adding the constraints - better to barf on bad insert rather than confuse later.
