### ISSUE TITLE
Cart approved and status attributes need better POD

### ISSUE THREAD

**Issue by SysPete** [interchange/interchange6-schema#135]
Result::Cart has 2 attrs that are not clear to me: status and approved. Anyone who can shed light is invited to improve the pod.

**Comment by SysPete** [comment]
Does anyone have input on this? Otherwise I'll be removing status and approved from Cart.

**Comment by sbatschelet** [comment]
I don't see why a cart would need 'approval' in the current way cart is used.  Would it be useful to define a cart status as saved or wishlist or abandoned?

**Comment by SysPete** [comment]
Carts for 'wishlist' or similar should be achieved by setting name to
'wishlist' (or whatever). Status is still a mystery to me.

**Comment by sbatschelet** [comment]
+1 for removal of both

**Comment by racke** [comment]
OK, let's get rid of these.
