### ISSUE TITLE
remove shipping_method from Order

### ISSUE THREAD

**Issue by sbatschelet** [interchange/interchange6-schema#139]
Because an order can have multiple shipping methods perhaps this should get replaced with a helper method that would return a list of methods used in the order.

**Comment by sbatschelet** [comment]
@SysPete what do you think about this?  An order can have multiple shipping_methods each which is set in Shipment.pm.  So setting a single field to define this seems wrong.

Example is an order with 3 items.  2 items are shipped from local stock via UPS Ground.  The other item is drop shipped from the manufacturer vis USPS Priority mail.  What is the value for shipping_method in Order?

**Comment by SysPete** [comment]
Agree. I think we should we should remove this column. @racke ?

**Comment by SysPete** [comment]
This issue is covered in more detail in #157 so closing this as duplicate.
