### ISSUE TITLE
add Result/MediaMessage class

### ISSUE THREAD

**Issue by sbatschelet** [interchange/interchange6-schema#152]
Messages such as blogs and reviews could/will require media and this media should be controlled by the schema.  This simple linker class will add a Media relationship to Message class.  

see PR #153

**Comment by SysPete** [comment]
Generally images in blogs/reviews would be linked via img tags in html (or markdown/whatever) content so I'm not sure why we'd want a direct relationship in the database.

**Comment by sbatschelet** [comment]
this functionality although imo useful for asset mgt is probably too specific for the schema at this point.
