### ISSUE TITLE
archiving orders

### ISSUE THREAD

**Issue by sbatschelet** [interchange/interchange6-schema#154]
IMO we require an archived option for the Order class view.  Using the field status to hold the value of archived seems very a limiting use.  I propose.

```
=head2 archived

Is this order archived?  Default is no.

=cut

column archived => {
    data_type         => "boolean",
    default_value     => 0,
};
```

**Comment by SysPete** [comment]
I'm not sure how this is better than just setting status to 'archived'. We don't want to add fields that can be handled by what we already have.

**Comment by sbatschelet** [comment]
Well an example of the limitation

order.status = complete,shipped,cancelled,foo

Now you want to archive the order.  You basically need to overwrite the value of the field. By adding an archive field this is a separate thing.

**Comment by SysPete** [comment]
@racke objections? If not then I'll implement.

**Comment by racke** [comment]
Another idea would be to track the order status in another table. I also think it is less than optimal to overwrite order status on changes.
