### ISSUE TITLE
Relationship between payment_orders and sessions

### ISSUE THREAD

**Issue by murwiz** [interchange/interchange6-schema#155]
My version of the schema may be out of date, but I have this:

    TABLE "payment_orders" CONSTRAINT "payment_orders_fk_sessions_id" FOREIGN KEY (sessions_id) REFERENCES sessions(sessions_id) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE

That's actually awkward, as it means you can never expire old sessions, or the associated payment row disappears, too. I believe this should be:

    TABLE "payment_orders" CONSTRAINT "payment_orders_fk_sessions_id" FOREIGN KEY (sessions_id) REFERENCES sessions(sessions_id) ON UPDATE CASCADE ON DELETE SET NULL DEFERRABLE

**Comment by murwiz** [comment]
Oh, and if that suggestion is taken:

 sessions_id           | character varying(255)      | not null

We must remove the "not null" constraint here.

**Comment by SysPete** [comment]
Closed by 012ba545 on 5th Oct 2014.
