### ISSUE TITLE
Message: Format and Parent

### ISSUE THREAD

**Issue by racke** [interchange/interchange6-schema#156]
We could easily extend Message to be used for Wiki nodes and comments. In that case it would be nice to have columns for parent_id and  format (plain text, HTML, Markdown, ...).

What do you think?
  
        Racke

**Comment by sbatschelet** [comment]
+1

**Comment by SysPete** [comment]
I guess Tree::AdjacencyList is a good option since we already use it in Navigation.

**Comment by racke** [comment]
Yeah, right.
