### ISSUE TITLE
Address query crash

### ISSUE THREAD

**Issue by racke** [interchange/interchange6-schema#159]
Why does this crashes when we have last_modified field present?

```
DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::mysql::st execute failed: Unknown column 'last_modified DESC' in 'order clause' [for Statement "SELECT `me`.`addresses_id`, `me`.`users_id`, `me`.`type`, `me`.`archived`, `me`.`first_name`, `me`.`last_name`, `me`.`company`, `me`.`address`, `me`.`address_2`, `me`.`postal_code`, `me`.`city`, `me`.`phone`, `me`.`states_id`, `me`.`country_iso_code`, `me`.`created`, `me`.`last_modified` FROM `addresses` `me` WHERE ( ( `type` = ? AND `users_id` = ? ) ) ORDER BY `last_modified DESC` LIMIT ?" with ParamValues: 0='billing', 1='4', 2=1] 
```

Code:

```
my $bill_adr = shop_address->search(
        {
            users_id => session('logged_in_user_id'),
            type => 'billing',
        },
        {
            order_by => 'last_modified DESC',
            rows => 1,
        },
```

**Comment by racke** [comment]
This fixes the issue: `order_by => {-desc => 'last_modified'},`.
I would appreciate explanation and documentation on this fact.

**Comment by SysPete** [comment]
SQLA expects -desc => 'last_modified' as per https://metacpan.org/pod/SQL::Abstract#ORDER-BY-CLAUSES and sees 'last_modified DESC' as a column name which does not exist.

**Comment by racke** [comment]
Somehow I had the impression that this worked at some point :-).
Thanks, @SysPete

**Comment by SysPete** [comment]
It would work if you passed the value as a literal:
```
order_by => \'last_modified DESC'
```
but literals should be avoided whenever possible since it prevents dbic from doing its usual cleanup and collapsing properly and sometimes results in weird behaviour.
