### ISSUE TITLE
Automatically create uri on insert for Product and Navigation

### ISSUE THREAD

**Issue by racke** [interchange/interchange6-schema#160]
What do you think about creating value for uri column automatically in case there is no value provided?

**Comment by SysPete** [comment]
something along the lines of this for nav:
```
$uri = lc( unidecode( $self->name ));
$uri =~ s{[\s/]+}{-}g;
```
and this for prod:

```
$uri = lc( unidecode( join( "-", $self->name, $self->sku )));
$uri =~ s{[\s/]+}{-}g;
```
?

**Comment by racke** [comment]
What is `unidecode` doing? And I wouldn't do lc. Most fun would be if this method can be overridden in subclass.

**Comment by SysPete** [comment]
unidecode transliterates utf8 into us ascii:
https://metacpan.org/pod/Text::Unidecode
so things like ® become (R) and you avoid weird utf8 issues.

Since this would be implemented by overriding the `new` method we could have `new` call some other method like `generate_uri` and then that would be the method to override.

**Comment by racke** [comment]
I'm not convinced of unidecode. If you have a Chinese shop, wouldn't you use Chinese URLs?
Or Russian?

Dancer should resolve that anyway, but having a test for this in DPIC6 would be nice probably.

I agree about `generate_uri`. It would be create to have some way to inject configuration (like what kind of filters you use in `generate_uri`) into the schema.

**Comment by SysPete** [comment]
Filters could be stored in `Setting`:
```
{
    scope => 'Product',
    name => 'generate_uri_filter',
    value => '$uri =~ s/badstuff/goodstuff/gi',
},
{
    scope => 'Product',
    name => 'generate_uri_filter',
    value => '$uri = lc($uri)',
},
```
Then we have something like this in Product:
```
use Encode;
sub new {
    my ( $class, $attrs ) = @_;
    unless ( $attrs->{uri} ) {
        $attrs->{uri} = $class->generate_uri( $attrs );
    }
    my $new = $class->next::method($attrs);
    return $new;
}
sub generate_uri {
    my ( $class, $attrs ) = @_;
    my $uri = decode( join( "-", $attrs->{name}, $attrs->{sku} ));
    $uri =~ s{[\s/]+}{-}g; # space and /
    my $filters = $class->result_source->schema->resultset('Setting')->search(
        {
            scope => 'Product',
            name => 'generate_uri_filter',
        }
    );
    while ( my $filter = $filters->next ) {
        eval $filter->value;
        $class->throw_exception("Product generate_uri: $@") if $@; 
    }
    return encode($uri));
}
```
Then you can either add things to `Setting` or you can override `generate_uri` and do your own thing.

**Comment by racke** [comment]
Ok sounds good.
