### ISSUE TITLE
NetBSD smoker failure

### ISSUE THREAD

**Issue by SysPete** [interchange/interchange6-schema#169]
http://www.cpantesters.org/cpan/report/a6011ac0-cb9e-11e4-adfb-e2d3ebda7229

make: 
make: stopped in /home/cpan/pit/bare/conf/perl-5.16.3/.cpanplus/5.16.3/build/Interchange6-Schema-0.080
no target to make.

**Comment by SysPete** [comment]
Managed to repeat this in a local VM:
Building and testing Interchange6-Schema-0.080
make: no target to make.

**Comment by SysPete** [comment]
Good old NetBSD's make isn't GNU make but the generated Makefile doesn't work with BSD make. Running gmake instead of make and all is fine. Not sure about the fix for this yet.

**Comment by racke** [comment]
Isn't that a Perl bug?

**Comment by SysPete** [comment]
Also one of the reasons not to use EUMM and switch to a PP builder.

**Comment by racke** [comment]
What's PP?

**Comment by SysPete** [comment]
pure perl - no make.

**Comment by racke** [comment]
Which one do you like?

**Comment by SysPete** [comment]
I don't think there is one that doesn't suck in too may ways (sadly). Interesting to note than MI-based packages like DBIC installed without issue so I need to see what MI is doing to make EUMM not barf on bsd's make.

**Comment by SysPete** [comment]
<racke> it is a recent release
<racke> but so they screwed up Perl IMHO
<racke> let's close it
<SysPete> k
<racke> perl should know that it should use gmake
<racke> period
<racke> not our fault
<SysPete> agree

**Comment by racke** [comment]
Actually a bug in Makefile.PL ... 930309040eac620a884b00249a73dd60bd59e688
