### ISSUE TITLE
Uses File::Slurp, known to be buggy and vulnerable

### ISSUE THREAD

**Issue by karenetheridge** [interchange/interchange6-schema#171]
e.g. look at https://rt.cpan.org/Ticket/Display.html?id=83126 and be dismayed

File::Slurp::Tiny and Path::Tiny are both excellent alternatives. See also http://shadow.cat/blog/matt-s-trout/mstpan-5/

**Comment by SysPete** [comment]
Thanks for the heads up @karenetheridge - I hadn't realised how nasty it was. Use here is a quick slurp in a test script so will switch to simple undef $/ and slurp via <>.
