### ISSUE TITLE
default billing and shipping address

### ISSUE THREAD

**Issue by sbatschelet** [interchange/interchange6-schema#175]
A user can have many addresses but from what I can tell we can not define a default for shipping or billing.  One way this could be accomplished is to add a billing_address_id and shipping_address_id to User.  Then we can have an address book of addresses but the defaults are directly set in User.  This allows us to populate user forms with defined defaults.

**Comment by SysPete** [comment]
Not keen on adding columns to User for this. I think I'd prefer priority
column in Address. You could set priority to 10000 for default address
and then increment priority by 1 each time an address is used so you
present address options in a sensible order.

**Comment by racke** [comment]
Yeah priority makes sense to me as well. I would use 1 for default address and 0 otherwise.
That's good enough for the regular shop, but allow flexibility for special shops / customers.

**Comment by sbatschelet** [comment]
:+1: thanks
