### ISSUE TITLE
proposal: make Navigation uri column nullable

### ISSUE THREAD

**Issue by SysPete** [interchange/interchange6-schema#178]
This is handy in some instances where I want a parent nav that doesn't need (or want) a uri. If this change is made then we also need to remove the override of insert which auto-generates uri from name.

**Comment by sbatschelet** [comment]
With a the large range of functionality of the Navigation class I think this will add additional usability for menus.  @racke do you currently use the auto-gen ^^.

**Comment by racke** [comment]
Yes, I'm using the autogeneration. Can't we force NULL value by passing NULL when we create Navigation record?

**Comment by SysPete** [comment]
At the moment we override insert at which point the object is fully 
inflated so we can't tell whether uri was passed as an undef arg or not 
passed at all. Perhaps the autogen stuff could be moved elsewhere - to 
be investigated.
