### ISSUE TITLE
Tests fail (with Locale::SubCountry 2.00?)

### ISSUE THREAD

**Issue by eserte** [interchange/interchange6-schema#201]
More information:
* Statistical analysis (currently it seems likely that the failure is caused by Locale::SubCountry 2.00): http://analysis.cpantesters.org/solved?distv=Interchange6-Schema-0.130
* testers reports: http://matrix.cpantesters.org/?dist=Interchange6-Schema%200.130

**Comment by SysPete** [comment]
Many thanks @eserte
