### ISSUE TITLE
Easy return of all attributes for a product

### ISSUE THREAD

**Issue by rmtemplet** [interchange/interchange6-schema#86]
Sam helped me out a ton on Friday but it still took me almost all day to just return the attributes for a product. This is what we ended up with to do the work:

my $sku = '1029';
$data = shop_product->find($sku)->search_attributes;
 while ( my $row = $data->next ) {
    my $product = shop_product($sku);
    my $attr_value = $product->find_attribute_value($row->name);
}

It would be real handy if we could make a helper(?) that would allow us to fetch them all in one call like:

$schema->fetch_all_attributes($sku) or something.

**Comment by SysPete** [comment]
@murwiz does the search_attribute_values method resolve your issue?

**Comment by SysPete** [comment]
Seems to me that search_attribute_values method solves this. Closing.
